#!/bin/bash -x

FSTI_BASE=`dirname "$0"`

if [ "$1" == "release" ]; then
    COMPDIR=$FSTI_BASE/release/
    EXE=$FSTI_BASE/release/src/faststi
else
    COMPDIR=$FSTI_BASE/debug/
    EXE=$FSTI_BASE/debug/src/faststi
fi

CURRENT_DIR=`pwd`
echo $CURRENT_DIR
cd $COMPDIR
ninja
cd $CURRENT_DIR

if [ -z ${var+x} ]; then
    FSTI_DATA=$FSTI_BASE/data $EXE $*
else
    $EXE $*
fi
