#!/bin/bash

FSTI_BASE=`dirname "$0"`

if [ "$#" -ne 1 ]; then
    echo "Directory name missing"
    echo "Usage: "$0" create <directory>"
    exit 1
else
    if [ ! -d "$1" ]; then
        mkdir "$1"
    fi
    cp -rf "$FSTI_BASE/"* "$1/"
fi

cd "$1"
if [ -f fsti ]; then
    rm fsti
fi
ln -s fstirun fsti
